package collector

import (
	"context"
	"log/slog"
	"strings"
	"time"

	"github.com/argus/ecs-fargate-agent/internal/config"
	"github.com/argus/ecs-fargate-agent/internal/metadata"
	"github.com/argus/ecs-fargate-agent/internal/telemetry"
)

type Collector struct {
	client metadata.Client
	task   metadata.Task
	cfg    config.Config
	logger *slog.Logger
}

func New(client metadata.Client, task metadata.Task, cfg config.Config, logger *slog.Logger) *Collector {
	return &Collector{client: client, task: task, cfg: cfg, logger: logger}
}

func (c *Collector) Collect(ctx context.Context) (telemetry.Snapshot, error) {
	stats, err := c.client.TaskStats(ctx)
	if err != nil {
		return telemetry.Snapshot{}, err
	}
	containers := mapContainers(c.task.Containers)
	samples := make([]telemetry.ContainerSample, 0, len(stats))
	now := time.Now().UTC()

	for key, st := range stats {
		container := containers[key]
		if container.Name == "" {
			container = containers[st.ID]
		}
		name := firstNonEmpty(container.Name, st.Name, key)
		if strings.EqualFold(name, "probe-sidecar") {
			continue
		}
		rxBytes, txBytes, rxPackets, txPackets := networkTotals(st.Networks)
		blkRead, blkWrite := blockTotals(st.BlkIO)
		memPercent := percent(float64(st.Memory.Usage), float64(st.Memory.Limit))
		samples = append(samples, telemetry.ContainerSample{
			ContainerID:   firstNonEmpty(container.DockerID, st.ID, key),
			ContainerName: name,
			Image:         container.Image,
			Status:        firstNonEmpty(container.KnownStatus, "UNKNOWN"),
			CPUPercent:    CPUPercent(st),
			MemUsageBytes: st.Memory.Usage,
			MemLimitBytes: st.Memory.Limit,
			MemPercent:    memPercent,
			NetRxBytes:    rxBytes,
			NetTxBytes:    txBytes,
			NetRxPackets:  rxPackets,
			NetTxPackets:  txPackets,
			BlkReadBytes:  blkRead,
			BlkWriteBytes: blkWrite,
			RestartCount:  0,
			Timestamp:     firstTime(st.Timestamp, st.Read, now),
			Labels:        c.labels(container),
		})
	}

	return telemetry.Snapshot{
		Samples: samples,
		Logs:    mockLogs(c.cfg, c.task, now),
	}, nil
}

func CPUPercent(st metadata.ContainerStats) float64 {
	cpuDelta := float64(st.CPUStats.CPUUsage.TotalUsage - st.PreCPU.CPUUsage.TotalUsage)
	systemDelta := float64(st.CPUStats.SystemCPUUsage - st.PreCPU.SystemCPUUsage)
	online := float64(st.CPUStats.OnlineCPUs)
	if online == 0 {
		online = float64(len(st.CPUStats.CPUUsage.PercpuUsage))
	}
	if cpuDelta <= 0 || systemDelta <= 0 || online <= 0 {
		return 0
	}
	return (cpuDelta / systemDelta) * online * 100
}

func (c *Collector) labels(container metadata.Container) map[string]string {
	return map[string]string{
		"probe.environment":       c.cfg.Environment,
		"service.name":            c.cfg.ServiceName,
		"ecs.cluster.arn":         c.task.Cluster,
		"ecs.task.arn":            c.task.TaskARN,
		"ecs.task.family":         c.task.Family,
		"ecs.task.revision":       c.task.Revision,
		"ecs.launch_type":         c.task.LaunchType,
		"cloud.availability_zone": c.task.AvailabilityZone,
		"container.image.name":    container.Image,
		"container.id":            container.DockerID,
	}
}

func mockLogs(cfg config.Config, task metadata.Task, ts time.Time) []telemetry.LogLine {
	if task.TaskARN == "" || cfg.Environment != "local" {
		return nil
	}
	return []telemetry.LogLine{
		{
			Timestamp:     ts,
			Severity:      "info",
			Message:       "local mock log generated by Probe ECS sidecar",
			ContainerName: cfg.ServiceName,
			Stream:        "stdout",
			Labels: map[string]string{
				"probe.environment": cfg.Environment,
				"ecs.task.arn":      task.TaskARN,
			},
		},
	}
}

func mapContainers(in []metadata.Container) map[string]metadata.Container {
	out := make(map[string]metadata.Container, len(in)*2)
	for _, c := range in {
		if c.DockerID != "" {
			out[c.DockerID] = c
		}
		if c.Name != "" {
			out[c.Name] = c
		}
	}
	return out
}

func networkTotals(nets metadata.Networks) (rxBytes, txBytes, rxPackets, txPackets uint64) {
	for _, n := range nets {
		rxBytes += n.RxBytes
		txBytes += n.TxBytes
		rxPackets += n.RxPackets
		txPackets += n.TxPackets
	}
	return
}

func blockTotals(blk metadata.BlkIOStats) (read, write uint64) {
	for _, entry := range blk.IoServiceBytesRecursive {
		switch strings.ToLower(entry.Op) {
		case "read":
			read += entry.Value
		case "write":
			write += entry.Value
		}
	}
	return
}

func percent(value, total float64) float64 {
	if total <= 0 {
		return 0
	}
	return value / total * 100
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

func firstTime(values ...time.Time) time.Time {
	for _, v := range values {
		if !v.IsZero() {
			return v
		}
	}
	return time.Now().UTC()
}
