// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: hermes/v1/hermes.proto

package hermespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ingest_PushBatch_FullMethodName     = "/argus.hermes.v1.Ingest/PushBatch"
	Ingest_StreamBatches_FullMethodName = "/argus.hermes.v1.Ingest/StreamBatches"
)

// IngestClient is the client API for Ingest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ingest is the agent -> poller telemetry channel. The Fargate sidecar
// (codebase 2) is the client; the poller (codebase 1) is the server.
//
// Two RPCs on purpose:
//
//	PushBatch     - simple unary, one batch per flush. Easiest to load-balance
//	                through an ALB/NLB and reason about.
//	StreamBatches - client-streaming, one long-lived connection per task. Lower
//	                per-message overhead for high-frequency / many-container
//	                tasks; the connection itself is the liveness signal.
//
// Authentication is per-RPC HMAC carried in gRPC metadata (see transport/auth);
// transport security is TLS/mTLS (see transport/tls). The tenant is NEVER taken
// from the payload — the server binds it from the authenticated agent identity.
type IngestClient interface {
	PushBatch(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*PushAck, error)
	StreamBatches(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Batch, StreamSummary], error)
}

type ingestClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestClient(cc grpc.ClientConnInterface) IngestClient {
	return &ingestClient{cc}
}

func (c *ingestClient) PushBatch(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*PushAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushAck)
	err := c.cc.Invoke(ctx, Ingest_PushBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestClient) StreamBatches(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Batch, StreamSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ingest_ServiceDesc.Streams[0], Ingest_StreamBatches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Batch, StreamSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingest_StreamBatchesClient = grpc.ClientStreamingClient[Batch, StreamSummary]

// IngestServer is the server API for Ingest service.
// All implementations must embed UnimplementedIngestServer
// for forward compatibility.
//
// Ingest is the agent -> poller telemetry channel. The Fargate sidecar
// (codebase 2) is the client; the poller (codebase 1) is the server.
//
// Two RPCs on purpose:
//
//	PushBatch     - simple unary, one batch per flush. Easiest to load-balance
//	                through an ALB/NLB and reason about.
//	StreamBatches - client-streaming, one long-lived connection per task. Lower
//	                per-message overhead for high-frequency / many-container
//	                tasks; the connection itself is the liveness signal.
//
// Authentication is per-RPC HMAC carried in gRPC metadata (see transport/auth);
// transport security is TLS/mTLS (see transport/tls). The tenant is NEVER taken
// from the payload — the server binds it from the authenticated agent identity.
type IngestServer interface {
	PushBatch(context.Context, *Batch) (*PushAck, error)
	StreamBatches(grpc.ClientStreamingServer[Batch, StreamSummary]) error
	mustEmbedUnimplementedIngestServer()
}

// UnimplementedIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServer struct{}

func (UnimplementedIngestServer) PushBatch(context.Context, *Batch) (*PushAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PushBatch not implemented")
}
func (UnimplementedIngestServer) StreamBatches(grpc.ClientStreamingServer[Batch, StreamSummary]) error {
	return status.Error(codes.Unimplemented, "method StreamBatches not implemented")
}
func (UnimplementedIngestServer) mustEmbedUnimplementedIngestServer() {}
func (UnimplementedIngestServer) testEmbeddedByValue()                {}

// UnsafeIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServer will
// result in compilation errors.
type UnsafeIngestServer interface {
	mustEmbedUnimplementedIngestServer()
}

func RegisterIngestServer(s grpc.ServiceRegistrar, srv IngestServer) {
	// If the following call panics, it indicates UnimplementedIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ingest_ServiceDesc, srv)
}

func _Ingest_PushBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Batch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServer).PushBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingest_PushBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServer).PushBatch(ctx, req.(*Batch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingest_StreamBatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServer).StreamBatches(&grpc.GenericServerStream[Batch, StreamSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingest_StreamBatchesServer = grpc.ClientStreamingServer[Batch, StreamSummary]

// Ingest_ServiceDesc is the grpc.ServiceDesc for Ingest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ingest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.hermes.v1.Ingest",
	HandlerType: (*IngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushBatch",
			Handler:    _Ingest_PushBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBatches",
			Handler:       _Ingest_StreamBatches_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "hermes/v1/hermes.proto",
}
