// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v7.34.1
// source: proto/hermes/v1/hermes.proto

package hermespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Ingest_PushBatch_FullMethodName     = "/argus.hermes.v1.Ingest/PushBatch"
	Ingest_StreamBatches_FullMethodName = "/argus.hermes.v1.Ingest/StreamBatches"
)

// IngestClient is the client API for Ingest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestClient interface {
	PushBatch(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*PushAck, error)
	StreamBatches(ctx context.Context, opts ...grpc.CallOption) (Ingest_StreamBatchesClient, error)
}

type ingestClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestClient(cc grpc.ClientConnInterface) IngestClient {
	return &ingestClient{cc}
}

func (c *ingestClient) PushBatch(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*PushAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushAck)
	err := c.cc.Invoke(ctx, Ingest_PushBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestClient) StreamBatches(ctx context.Context, opts ...grpc.CallOption) (Ingest_StreamBatchesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ingest_ServiceDesc.Streams[0], Ingest_StreamBatches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &ingestStreamBatchesClient{ClientStream: stream}
	return x, nil
}

type Ingest_StreamBatchesClient interface {
	Send(*Batch) error
	CloseAndRecv() (*StreamSummary, error)
	grpc.ClientStream
}

type ingestStreamBatchesClient struct {
	grpc.ClientStream
}

func (x *ingestStreamBatchesClient) Send(m *Batch) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ingestStreamBatchesClient) CloseAndRecv() (*StreamSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IngestServer is the server API for Ingest service.
// All implementations must embed UnimplementedIngestServer
// for forward compatibility
type IngestServer interface {
	PushBatch(context.Context, *Batch) (*PushAck, error)
	StreamBatches(Ingest_StreamBatchesServer) error
	mustEmbedUnimplementedIngestServer()
}

// UnimplementedIngestServer must be embedded to have forward compatible implementations.
type UnimplementedIngestServer struct {
}

func (UnimplementedIngestServer) PushBatch(context.Context, *Batch) (*PushAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushBatch not implemented")
}
func (UnimplementedIngestServer) StreamBatches(Ingest_StreamBatchesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamBatches not implemented")
}
func (UnimplementedIngestServer) mustEmbedUnimplementedIngestServer() {}

// UnsafeIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServer will
// result in compilation errors.
type UnsafeIngestServer interface {
	mustEmbedUnimplementedIngestServer()
}

func RegisterIngestServer(s grpc.ServiceRegistrar, srv IngestServer) {
	s.RegisterService(&Ingest_ServiceDesc, srv)
}

func _Ingest_PushBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Batch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServer).PushBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingest_PushBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServer).PushBatch(ctx, req.(*Batch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingest_StreamBatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServer).StreamBatches(&ingestStreamBatchesServer{ServerStream: stream})
}

type Ingest_StreamBatchesServer interface {
	SendAndClose(*StreamSummary) error
	Recv() (*Batch, error)
	grpc.ServerStream
}

type ingestStreamBatchesServer struct {
	grpc.ServerStream
}

func (x *ingestStreamBatchesServer) SendAndClose(m *StreamSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ingestStreamBatchesServer) Recv() (*Batch, error) {
	m := new(Batch)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Ingest_ServiceDesc is the grpc.ServiceDesc for Ingest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ingest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.hermes.v1.Ingest",
	HandlerType: (*IngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushBatch",
			Handler:    _Ingest_PushBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBatches",
			Handler:       _Ingest_StreamBatches_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hermes/v1/hermes.proto",
}
